### PR TITLE
Add "add Checkitem"

### PR DESCRIPTION
**Pull request by powermosfet**
Added a new node for adding checkitems to checklists

### CODE REVIEW

**Comment by oliverlorenz** [comment]
Hey! This is amazing! I really like it! But: While checking your change, I recognized that nothing is working. Not only your new node. also the original node.

I could fix this but I'm a little bit confused about that. I identified that the problem is "msg.trello" for example here:

`sendData.name = msg.trello.name ? msg.trello.name : config.name`

**Comment by oliverlorenz** [comment]
Hey! This is amazing! I really like it! But: While checking your change, I recognized that nothing is working. Not only your new node. also the original node.

I could fix this but I'm a little bit confused about that. I identified that the problem is "msg.trello" for example here:

trello/81_trello-add-card.js
`sendData.name = msg.trello.name ? msg.trello.name : config.name`

The property "msg.trello" is undefined. The propertyíes are now attached to "msg" itself. I saw that you used the same pattern and I think you tested your code, so why this is working at your setup?

Which node and node-red version you used? Maybe there is a change I missed. I used node 6.10 and node-red 0.16.2. I installed this node with `npm install` manually.

**Comment by powermosfet** [comment]
Nice to hear that you like it 😄 

I have node 6.9.2 and node-red 0.16.2, and I tested it by running `npm link` from my project folder and then `npm link node-red-contrib-trello` in the node-red folder.

I didn't have this issue when i used these nodes myself, since my msg actually had a trello object on it.

I added a commit now that handles this by defaulting to an empty object if msg.trello is not there.
What do you think?

**Comment by oliverlorenz** [comment]
cool! Its working perfectly! Thanks for your contribution!

**Comment by oliverlorenz** [comment]
OK. Version 0.1.0 is released at npm: https://www.npmjs.com/package/node-red-contrib-trello

**Pull request merged**
